version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/

  job:
    build:
      context: .
      dockerfile: job.Dockerfile
    depends_on:
      - database
    volumes:
      - ./app:/usr/src/app
    tty: true

  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"
    # volumes:
    #   - ./database/data:/var/lib/mysql
