version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

  job:
    build:
      context: .
      dockerfile: job.Dockerfile
    restart: always
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database
    tty: true

  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    env_file:
      - ./database/.env
