version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: api-prod.Dockerfile
    restart: always
    depends_on:
      - database
    tty: true

  job:
    build:
      context: ./backend
      dockerfile: job-prod.Dockerfile
    restart: always
    depends_on:
      - database
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx-prod.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/public:/usr/share/nginx/html
    depends_on:
      - api

  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    restart: always
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    env_file:
      - ./database/.env
