version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database

  job:
    build:
      context: ./backend
      dockerfile: job.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database
    tty: true

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql_init:/docker-entrypoint-initdb.d
      - ./database/conf.d:/etc/mysql/conf.d
      - ./mysql_data:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - BIND-ADDRESS=0.0.0.0
    env_file:
      - .env
