version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

  job:
    build:
      context: ./backend
      dockerfile: job.Dockerfile
    restart: always
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/public:/usr/share/nginx/html
    depends_on:
      - api

  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    env_file:
      - ./database/.env
