version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database

  job:
    build:
      context: ./backend
      dockerfile: job.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database
    tty: true

  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    env_file:
      - .env
