version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app

  job:
    build:
      context: .
      dockerfile: job.Dockerfile
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app
    tty: true

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/usr/share/nginx/html

  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"
    # volumes:
    #   - ./database/data:/var/lib/mysql
