- hosts: backend
  tasks:
    - name: message
      debug: 
        msg: Start initialize

    - name: yum update
      yum:
        name: "*"
        state: latest
      become: true

    - name: enable epel-release
      command:
        cmd: amazon-linux-extras install epel -y
      become: true

    - name: install docker
      include_role:
        name: docker
    
    - name: install git
      include_role:
        name: git

    - name: deploy app
      include_role:
        name: app
      vars:
        run_service: false

    - name: get cert
      include_role:
        name: cert
      vars:
        get_cert: true

    - name: set cron
      include_role:
        name: cron
      