- name: hourly job to update all data
  cron:
    name: job to update all data
    minute: "30"
    hour: "0-2,4-23"
    job: 'docker-compose exec job bash -c "go run *.go issue"'
    state: present
  become: true
  
- name: daily job to update issue
  cron:
    name: job to update issue
    minute: "30"
    hour: "3"
    job: 'docker-compose exec job bash -c "go run *.go all"'
    state: present
  become: true
