- name: hourly job to update all data
  cron:
    name: job to update all data
    minute: "30"
    hour: "0-2,4-23"
    job: 'docker-compose -f docker-compose-prod.yml exec job bash -c "job issue"'
    state: present
  become: true
  
- name: daily job to update issue
  cron:
    name: job to update issue
    minute: "30"
    hour: "3"
    job: 'docker-compose -f docker-compose-prod.yml exec job bash -c "job all"'
    state: present
  become: true

- name: register crontab
  command: crontab -l
  register: crontab
  become: true

- name: print crontab
  debug:
    msg: "{{ crontab.stdout_lines }}"