- name: set facts
  set_fact:
    backend_dir_path: "{{ ansible_env.PWD }}/../backend"

- name: build image
  command:
    cmd: "docker image build -t {{ image_prefix }}-{{ item }}:{{ image_tag }} -f {{ item }}-prod.Dockerfile ."
    chdir: "{{ backend_dir_path }}"
  with_items:
    - api
    - job

- name: push image
  command:
    cmd: "docker push {{ image_prefix }}-{{ item }}:{{ image_tag }}"
  with_items:
    - api
    - job
  when: env == "prod"
