- name: delete old envs
  command:
    cmd: "kubectl delete secret envs"
  ignore_errors: true

- name: set env file for local
  set_fact:
    env_file: .env
  when: env == "local"

- name: set env file for prod
  set_fact:
    env_file: .prodenv
  when: env == "prod"

- name: deploy envs
  command:
    cmd: "kubectl create secret generic envs --from-env-file={{ ansible_env.PWD }}/../{{ env_file }}"

- name: deploy app into local
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    template: "kubernetes/{{ item }}.yaml"
  with_items:
    - api
    - job
    - mongo
    - mongo-express
  when: env == "local"

- name: deploy app into prod
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    template: "kubernetes-prod/{{ item }}.yaml"
  with_items:
    - issuer
    - api
    - job
    - mongo
    - mongo-express
    - ingress
  when: env == "prod"
