---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: gitnavi/database
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: database
        envFrom:
        - secretRef:
            name: envs
  #       volumeMounts:
  #       - name: database-volume
  #         mountPath: /var/lib/mysql
  # volumeClaimTemplates:
  # - metadata:
  #     name: database-volume
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 5Gi
