---
- hosts: localhost
  gather_facts: true
  tasks:
  - name: set variables
    set_fact:
      env: local
      type: install

  - name: set context
    include_tasks: tasks/set_context.yml

  - name: deploy app
    include_role:
      name: app
