---
- hosts: localhost
  gather_facts: true
  tasks:
  - name: set variables
    set_fact:
      env: prod
      type: uninstall

  - name: set context
    include_tasks: tasks/set_context.yml

  - name: uninstall app
    include_role:
      name: app
